<?php
	$style = '';

	include("parsedown.php");
	$Parsedown = new Parsedown();

	include("filetypemap.php");


	$url = rtrim($_GET["url"],"/");
	function curlSite($url) {
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, $url);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

		curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

		$headers = array();
		$headers[] = 'Authority: api.github.com';
		$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7';
		$headers[] = 'Accept-Language: en-US,en;q=0.9';
		$headers[] = 'Cache-Control: max-age=0';
		$headers[] = 'If-None-Match: W/\"25d6ec983c3a714ddde957f456b9f1142c08d74b3e80cbe1cb8a8286f926e9ef\"';
		$headers[] = 'Sec-Ch-Ua: \"Not_A Brand\";v=\"8\", \"Chromium\";v=\"120\"';
		$headers[] = 'Sec-Ch-Ua-Mobile: ?0';
		$headers[] = 'Sec-Ch-Ua-Platform: \"Linux\"';
		$headers[] = 'Sec-Fetch-Dest: document';
		$headers[] = 'Sec-Fetch-Mode: navigate';
		$headers[] = 'Sec-Fetch-Site: none';
		$headers[] = 'Sec-Fetch-User: ?1';
		$headers[] = 'Upgrade-Insecure-Requests: 1';
		$headers[] = 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
			echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);
		return $result;
	}
	if(empty($url)) {
		?>
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="./style.css">
	</head>
	<body>
		<h1>ghviewer</h1>
		<p>is a simple site for stripping a github repo page down to a readme and the link for the source code. This is useful for many people who feel like they can't navigate GitHub and want the download link shown to them.</p>
		<a href="https://github.com/IoIxD/ghviewer">The source code is here.</a><br><br>
		<b>Put in a repo here:</b>
		<form action="" method="get">
			<input width="100%" type="text" name="url" placeholder="https://github.com/IoIxD/ghviewer/"></input>
		</form>
	</body>
</html>
		<?php
	} else {
		ini_set('display_errors', 1);
		ini_set('display_startup_errors', 1);
		error_reporting(E_ALL);
		$apiurl = str_replace("github.com","api.github.com/repos",$url);
		$releaseurl = $apiurl."/releases";

		$info = json_decode(curlSite($apiurl));
		$relinfo = json_decode(curlSite($releaseurl));

		$title = $info->{"name"};
		$default_branch = $info->{"default_branch"};
		$raw_url = str_replace("github.com","raw.githubusercontent.com",$url)."/".$default_branch;

		$readme_url = $raw_url."/README.md";
		$zip_url = $url."/zipball/master/";
		$tar_url = $url."/tarball/master/";

		$downloads = "";
		$has_downloads = false;
		if(count($relinfo) >= 1) {
			$has_downloads = true;
			foreach($relinfo as $item) {
				$downloads .= "<p class='downloads'>";
				$downloads .= "<h2>".$item->{"name"}."</h2><br>";
				$downloads .= "<table><tr style='font-weight: bold'><td>Downloads</td><td>About</td></tr>";

				$downloads .= "<tr><td>";
				
				foreach($item->{"assets"} as $asset) {
					$name = $asset->{"name"};
					$url = $asset->{"browser_download_url"};

					$ext = "";
					if (strpos($url, ".")) {
						$parts = explode(".",$name);
						$ext = $parts[count($parts)-1];
					}
					if($ext == $name) {
						$ext = "Linux: ";
					} else {
						$ext = $filetypemap[".".strtolower($ext)].": ";
					}
					$downloads .= "<a href=\"".$url."\">".$ext.$name."</a><br>";
				}
				$downloads .= "</td>";
				$downloads .= "<td width=\"50%\">".$Parsedown->text($item->{"body"})."</td></tr>";

				$downloads .= "</table>";
				$downloads .= "</p>";
			}
		}

		$htm = $Parsedown->text(curlSite($readme_url));
		$htm = preg_replace("/img src=\"(?!https)(.*?)\"/","img src=".$raw_url."/$1",$htm);
		$readme = $htm;
		?>
<html>
	<head>
	<link rel="stylesheet" type="text/css" href="./style.css">
	<title><?php echo $title?></title>
	</head>
	<body>
		<h1 style='text-align: center'><?php echo $title?></h1>
		<a style="font-size: 160%; margin: 0 auto; padding: 5px; 
			color: white; font-weight:bold; 
			background: linear-gradient(to bottom, #a83232,#802020);
			border-radius: 5px;"
		href="#downloads">Downloads</a>
		<br>
		<hr>
		<p id="readme">
			<?php echo $readme?></p>
		<hr>
		<p id="downloads">
		<h1>Downloads</h1>
		<?php 
		if($has_downloads) { 
			echo $downloads; 
		} else {?>
			<a href="<?php echo $zip_url?>">Download source code as .zip</a><br>
			<a href="<?php echo $tar_url?>">Download source code as .tar.gz</a><br>
				<?php
		}
			?>
		</p>
		<div style='display: block; height: 300%'></div>
	</body>
</html>
		<?php
	}
?>
